name: Question
description: Ask a question about Reliary usage, internals, or roadmap
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: What's your question?
      validations:
        required: true

  - type: textarea
    id: context
    attributes:
      label: Context (optional)
      description: What are you trying to do? What have you tried?
      validations:
        required: false
