#!/usr/bin/env python3
"""Reliary8-focused long session benchmark.

Tests the holographic pack on the reliary8 codebase itself, which DeepSeek has
NOT been trained on. This is where the pack should help most.

Conditions:
- A (reliary): reliary MCP tools only
- D (reliary+pack): reliary MCP tools + focused holographic pack pre-loaded

Queries come from the validation probes (50 comprehension + 13 reasoning) for
the 10 functions in reliary8's sift/output modules.

Usage:
  python3 bench/reliary8_session_bench.py --conditions A,D --seeds 42
"""
import argparse
import json
import os
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import multi_turn_harness as mth
from llm_conn import deepseek_chat

RELIARY8_ROOT = "$HOME/src/reliary8"
PROBES_PATH = HERE / "results" / "reliary8_probes.json"

# Focused pack: only the symbols the probes ask about
# This is generated by reading probe function names from the probe set
# and building a focused pack from those.

MAX_TURNS_PER_QUERY = 5  # hard cap per query to prevent runaway

def load_queries():
    with open(PROBES_PATH) as f:
        return json.load(f)

def build_focused_pack(queries):
    """Build a holographic pack containing ONLY the symbols referenced in queries.
    This keeps the pack small (10-20 symbols instead of 481)."""
    # Extract function names from probes
    funcs = set()
    for q in queries:
        rubric = q.get("rubric", {})
        fn = rubric.get("function")
        if fn:
            funcs.add(fn)
    # Always include the well-known ones even if not in rubric
    funcs.update({"skeleton", "aggressive_skeleton", "skeleton_hash", "classify_line",
                  "should_drop", "detect_strategy", "compress_content", "score"})
    funcs = sorted(funcs)
    # Run the pack generator, then filter
    import subprocess
    out = subprocess.run(
        [mth.RELIARY_BIN, "pack", RELIARY8_ROOT],
        capture_output=True, text=True, timeout=30,
        cwd=RELIARY8_ROOT
    )
    if out.returncode != 0:
        print(f"pack failed: {out.stderr[:300]}")
        return None
    full_pack = out.stdout
    # Filter: keep header + only entries whose ## name is in funcs
    lines = full_pack.split("\n")
    header = []
    body = []
    in_body = False
    current_entry = []
    current_name = None
    for line in lines:
        if line.startswith("## "):
            if current_entry and current_name in funcs:
                body.extend(current_entry)
            current_name = line[3:].split("/")[0].strip()
            current_entry = [line]
        elif line:
            current_entry.append(line)
        else:
            current_entry.append(line)
    if current_entry and current_name in funcs:
        body.extend(current_entry)
    focused = "\n".join(header) + "\n" + "\n".join(body)
    print(f"focused pack: {len(focused)} chars, {len(body)} lines, {len([l for l in body if l.startswith('## ')])} symbols")
    return focused

def install_pack_as_system_prompt(focused_pack):
    """Add condition D with focused pack pre-loaded."""
    # Clear existing D
    mth.SYSTEM_PROMPTS.pop("D", None)
    if focused_pack:
        pack_section = f"\n\n## Codebase reference (focused holographic pack)\n\n{focused_pack[:30000]}"
        mth.SYSTEM_PROMPTS["D"] = mth.RELIARY_SYS + pack_section
        mth.CONDITION_NAMES["D"] = "reliary+pack"
        mth.CONDITION_TOOLS["D"] = mth.RELIARY_TOOLS
# E: codebase-memory-mcp (the competitor)
mth.SYSTEM_PROMPTS["E"] = mth.ALTBACKEND_SYS
mth.CONDITION_NAMES["E"] = "cbm"
mth.CONDITION_TOOLS["E"] = mth.ALTBACKEND_TOOLS

def run_session(cond, queries, model, seed, timeout_total=1800):
    """Run a single session with the given queries."""
    rng_idx = seed  # for any randomness in tasks
    sys_prompt = mth.SYSTEM_PROMPTS[cond]
    mth._sessions.clear()
    if cond in ("A", "D"):
        mth._sessions["reliary"] = mth.MCPSession(mth.RELIARY_BIN, RELIARY8_ROOT, "reliary")
    if cond == "E":
        mth._sessions["altbackend"] = mth.MCPSession(mth.ALTBACKEND_BIN, RELIARY8_ROOT, "altbackend")
    messages = [{"role": "system", "content": sys_prompt}]
    metrics = {
        "cond": cond, "cond_name": mth.CONDITION_NAMES.get(cond, cond),
        "model": model, "seed": seed, "queries": [],
        "total_wall_time": 0, "total_tool_calls": 0, "total_turns": 0,
        "total_tokens_in": 0, "total_tokens_out": 0,
        "total_weighted_cost": 0, "total_tool_bytes": 0,
        "total_dead_end_calls": 0, "total_score": 0,
        "total_cached_tokens": 0,
    }
    t_start = time.time()
    for qi, query in enumerate(queries):
        if time.time() - t_start > timeout_total:
            break
        messages.append({"role": "user", "content": query["question"]})
        q_m = {"query_id": query["id"], "tool_calls": 0, "turns": 0,
               "tokens_in": 0, "tokens_out": 0, "weighted_cost": 0,
               "tool_bytes": 0, "dead_end_calls": 0, "score": 0, "answer": "",
               "tool_names": []}
        for turn in range(MAX_TURNS_PER_QUERY):
            if time.time() - t_start > timeout_total:
                q_m["answer"] = "(session timeout)"
                break
            if turn == MAX_TURNS_PER_QUERY - 1:
                messages.append({"role": "user",
                    "content": "Give your FINAL answer now. ONE LINE: {\"final\": true, \"answer\": \"...\"}"})
            resp = deepseek_chat(messages, model=model, max_tokens=800,
                                 timeout=60, disable_thinking=True)
            if "error" in resp:
                q_m["answer"] = f"(error: {str(resp['error'])[:200]})"
                break
            msg = resp.get("choices", [{}])[0].get("message", {})
            content = msg.get("content", "") or msg.get("reasoning_content", "")
            usage = resp.get("usage", {})
            q_m["tokens_in"] += usage.get("prompt_tokens", 0)
            q_m["tokens_out"] += usage.get("completion_tokens", 0)
            cached = usage.get("prompt_cache_hit_tokens", 0) or usage.get("cached_tokens", 0)
            metrics["total_cached_tokens"] += cached
            q_m["turns"] = turn + 1
            action_type, action = mth.parse_llm_response(content)
            if action_type == "final":
                q_m["answer"] = action.get("answer", content[:2000])
                q_m["weighted_cost"] = q_m["tokens_in"] + 4 * q_m["tokens_out"]
                break
            elif action_type == "tool":
                tool_name = action.get("tool", action.get("name", ""))
                tool_args = action.get("args", action.get("arguments", action))
                if isinstance(tool_args, str):
                    try:
                        tool_args = json.loads(tool_args) if tool_args.strip().startswith("{") else {"query": tool_args}
                    except Exception:
                        tool_args = {"query": tool_args}
                output, _ = mth.execute_tool(cond, tool_name, tool_args)
                q_m["tool_calls"] += 1
                q_m["tool_bytes"] += len(output.encode())
                q_m["tool_names"].append(tool_name)
                if any(output.strip().startswith(m) for m in ["(no ", "(no results)", "(no definition", "(no trace", "(no search", "(error", "(altbackend error", "(grep error", "(read error"]):
                    q_m["dead_end_calls"] += 1
                messages.append({"role": "assistant", "content": content})
                messages.append({"role": "user", "content": f"Tool result:\n{output[:4000]}"})
            else:
                q_m["answer"] = content[:2000]
                q_m["weighted_cost"] = q_m["tokens_in"] + 4 * q_m["tokens_out"]
                break
        q_m["score"] = mth.score_answer(query, q_m["answer"])
        if q_m["answer"] and not q_m["answer"].startswith("("):
            messages.append({"role": "assistant", "content": q_m["answer"]})
        for k in ["tokens_in", "tokens_out", "tool_calls", "turns",
                  "weighted_cost", "tool_bytes", "dead_end_calls", "score"]:
            metrics[f"total_{k}"] += q_m[k]
        metrics["queries"].append(q_m)
    metrics["total_wall_time"] = time.time() - t_start
    mth._close_sessions()
    return metrics

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--model", default="deepseek-v4-flash")
    p.add_argument("--seeds", nargs="+", type=int, default=[42])
    p.add_argument("--conditions", default="A,D")
    p.add_argument("--max-queries", type=int, default=10, help="cap probe count (for quick testing)")
    p.add_argument("--out", default=None)
    args = p.parse_args()
    queries = load_queries()[:args.max_queries]
    focused = build_focused_pack(queries) if "D" in args.conditions.split(",") else None
    install_pack_as_system_prompt(focused)
    out_path = args.out or f"results/reliary8_session_{int(time.time())}.jsonl"
    all_runs = []
    for seed in args.seeds:
        for cond in args.conditions.split(","):
            print(f"\n=== seed={seed} cond={cond} ({mth.CONDITION_NAMES.get(cond,cond)}) ===", file=sys.stderr)
            try:
                r = run_session(cond, queries, args.model, seed)
                all_runs.append(r)
                # Per-tool breakdown
                from collections import Counter
                all_tool_names = []
                for q in r["queries"]:
                    all_tool_names.extend(q.get("tool_names", []))
                tool_counts = Counter(all_tool_names)
                tool_str = ", ".join(f"{n}={c}" for n, c in tool_counts.most_common())
                print(f"  score={r['total_score']}/{len(queries)*3} wc={r['total_weighted_cost']} cached={r['total_cached_tokens']} t={r['total_wall_time']:.1f}s")
                print(f"  tools: {tool_str}")
            except Exception as e:
                print(f"ERROR: {e}", file=sys.stderr)
                all_runs.append({"cond": cond, "seed": seed, "error": str(e)})
            mth._close_sessions()
    RESULTS_DIR = HERE / "results"
    with open(RESULTS_DIR / Path(out_path).name, "w") as f:
        for r in all_runs:
            f.write(json.dumps(r) + "\n")
    print(f"\nDone. Output: {RESULTS_DIR / Path(out_path).name}")

if __name__ == "__main__":
    main()
