#!/usr/bin/env python3
"""Reliary8-focused long session benchmark.

Tests the holographic pack on the reliary8 codebase itself, which DeepSeek has
NOT been trained on. This is where the pack should help most.

Conditions:
- A (reliary): reliary MCP tools only
- D (reliary+pack): reliary MCP tools + focused holographic pack pre-loaded

Queries come from the validation probes (50 comprehension + 13 reasoning) for
the 10 functions in reliary8's sift/output modules.

Usage:
  python3 bench/reliary8_session_bench.py --conditions A,D --seeds 42
"""
import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path
from collections import Counter

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import multi_turn_harness as mth
from llm_conn import deepseek_chat

# Focused pack: only the symbols the probes ask about
# This is generated by reading probe function names from the probe set
# and building a focused pack from those.

MAX_TURNS_PER_QUERY = 5  # hard cap per query to prevent runaway

def load_queries(probes_path=None):
    """Load probes from file. probes_path can be absolute or relative to bench/."""
    if probes_path is None:
        probes_path = HERE / "results" / "reliary8_probes.json"
    p = Path(probes_path)
    if not p.is_absolute():
        p = HERE / p
    with open(p) as f:
        return json.load(f)

def build_focused_pack(queries, project):
    """Build a holographic pack containing ONLY the symbols referenced in queries.
    This keeps the pack small (10-20 symbols instead of 481)."""
    # Extract function names from probes
    funcs = set()
    for q in queries:
        rubric = q.get("rubric", {})
        fn = rubric.get("function")
        if fn:
            funcs.add(fn)
    # Always include the well-known ones even if not in rubric
    funcs.update({"skeleton", "aggressive_skeleton", "skeleton_hash", "classify_line",
                  "should_drop", "detect_strategy", "compress_content", "score"})
    funcs = sorted(funcs)
    # Run the pack generator, then filter
    out = subprocess.run(
        [mth.RELIARY_BIN, "pack", project],
        capture_output=True, text=True, timeout=30,
        cwd=project
    )
    if out.returncode != 0:
        print(f"pack failed: {out.stderr[:300]}")
        return None
    full_pack = out.stdout
    # Filter: keep header + only entries whose ## name is in funcs
    lines = full_pack.split("\n")
    header = []
    body = []
    in_body = False
    current_entry = []
    current_name = None
    for line in lines:
        if line.startswith("## "):
            if current_entry and current_name in funcs:
                body.extend(current_entry)
            current_name = line[3:].split("/")[0].strip()
            current_entry = [line]
        elif line:
            current_entry.append(line)
        else:
            current_entry.append(line)
    if current_entry and current_name in funcs:
        body.extend(current_entry)
    focused = "\n".join(header) + "\n" + "\n".join(body)
    print(f"focused pack: {len(focused)} chars, {len(body)} lines, {len([l for l in body if l.startswith('## ')])} symbols")
    return focused


def build_auto_pack(project):
    """Build a holographic pack using --auto (gate + hotspot selection).
    This is the production mode — no probe-knowledge needed."""
    out = subprocess.run(
        [mth.RELIARY_BIN, "pack", "--auto", project],
        capture_output=True, text=True, timeout=60,
        cwd=project
    )
    if out.returncode != 0:
        print(f"auto pack failed: {out.stderr[:300]}")
        return None
    pack = out.stdout
    # Count symbols
    n_symbols = sum(1 for l in pack.split("\n") if l.startswith("## "))
    print(f"auto pack: {len(pack)} chars, {n_symbols} symbols (gate + hotspot)")
    return pack if pack else None


def build_full_pack(project):
    """Build the FULL pack (all symbols) for query-time slicing.
    This is pre-built once; sliced per-query in condition F."""
    out = subprocess.run(
        [mth.RELIARY_BIN, "pack", project],
        capture_output=True, text=True, timeout=300,
        cwd=project
    )
    if out.returncode != 0:
        print(f"full pack failed: {out.stderr[:300]}")
        return None
    pack = out.stdout
    n_symbols = sum(1 for l in pack.split("\n") if l.startswith("## "))
    print(f"full pack: {len(pack)} chars, {n_symbols} symbols (for slicing)")
    return pack


def _extract_func_names_from_question(question):
    """Extract function names (with underscores) from a question string.
    
    Looks for identifiers matching [a-z][a-z0-9_]* that look like function
    names (contain underscores, not all caps, length > 3).
    """
    import re
    candidates = re.findall(r'\b[a-z][a-z0-9_]{3,}\b', question)
    # Prefer names with underscores (more likely function names)
    func_like = [c for c in candidates if "_" in c and len(c) > 5]
    if func_like:
        return func_like
    return candidates[:3]


def slice_pack_for_query(full_pack, query, top_k=10):
    """Slice the full pack for a specific query using the Python BM25 fallback.
    
    Always uses Python BM25 (the CLI slicer requires a project path and can't
    operate on an in-memory pack string).
    """
    return _slice_pack_python(full_pack, query, top_k)


def _slice_pack_python(full_pack, query, top_k):
    """Python fallback slicer — BM25 over pack entries."""
    import math
    from collections import Counter

    # Parse entries
    entries = []
    current_name = None
    current_header = ""
    current_body = ""
    for line in full_pack.split("\n"):
        if line.startswith("## "):
            if current_name:
                entries.append((current_name, current_header, current_body))
            current_name = line[3:].split("/")[0].strip()
            current_header = line
            current_body = ""
        elif current_name:
            current_body += line + "\n"
    if current_name:
        entries.append((current_name, current_header, current_body))

    if not entries:
        return ""

    # Tokenize
    def tokenize(text):
        return [w.lower() for w in text.split() if len(w) > 1]

    query_tokens = set(tokenize(query))
    if not query_tokens:
        return "\n".join(f"{h}\n{b}" for _, h, b in entries[:top_k])

    # BM25 scoring with substring fallback for abbreviation matching.
    # E.g., "findcl" should match "find_clusters" via prefix overlap.
    n_docs = len(entries)
    doc_tokens = [tokenize(f"{name} {body}") for name, _, body in entries]
    avgdl = sum(len(d) for d in doc_tokens) / max(n_docs, 1)

    # Document frequencies
    df = Counter()
    for dt in doc_tokens:
        for t in set(dt):
            for qt in query_tokens:
                if qt in t or t in qt:
                    df[t] += 1
                    break

    scored = []
    for i, (name, header, body) in enumerate(entries):
        dl = len(doc_tokens[i])
        tf = Counter(doc_tokens[i])
        score = 0.0
        for qt in query_tokens:
            d_freq = df.get(qt, 0)
            if d_freq == 0:
                continue
            idf = math.log((n_docs - d_freq + 0.5) / (d_freq + 0.5) + 1.0)
            term_freq = tf.get(qt, 0)
            if term_freq > 0:
                bm25 = idf * (term_freq * 2.2) / (term_freq + 1.2 * (1 - 0.75 + 0.75 * dl / max(avgdl, 1)))
                score += bm25
        # Name boost (includes substring/abbreviation matching)
        name_lower = name.lower()
        for qt in query_tokens:
            if name_lower == qt:
                score += 5.0
            elif qt in name_lower:
                score += 2.0
            elif name_lower.startswith(qt) or name_lower.split("_")[0].startswith(qt[:5]):
                # Handle abbreviations like "findcl" -> "find_clusters"
                score += 1.5
        scored.append((score, header, body))

    scored.sort(key=lambda x: -x[0])
    selected = [(h, b) for s, h, b in scored[:top_k] if s > 0]

    if not selected:
        return ""
    return "\n\n".join(f"{h}\n{b}" for h, b in selected)

def install_pack_as_system_prompt(focused_pack):
    """Add condition D with focused pack pre-loaded."""
    # Clear existing D
    mth.SYSTEM_PROMPTS.pop("D", None)
    if focused_pack:
        pack_section = f"\n\n## Codebase reference (focused holographic pack)\n\n{focused_pack[:60000]}"
        mth.SYSTEM_PROMPTS["D"] = mth.RELIARY_SYS + WARMUP_PROMPT + pack_section
        mth.CONDITION_NAMES["D"] = "reliary+pack"
        mth.CONDITION_TOOLS["D"] = mth.RELIARY_TOOLS
# Generic warmup prompt — forces the model to actively read the pack
# before answering. Proven to add +12% accuracy (Angle 1 experiment).
WARMUP_PROMPT = """

Before answering, quickly answer these warmup questions about the relevant function:
1. What does it return for empty/blank input?
2. What is a key surprise or edge case?
3. Which other functions call or interact with it?
Then answer the main question."""
mth.SYSTEM_PROMPTS["E"] = mth.ALTBACKEND_SYS
mth.CONDITION_NAMES["E"] = "cbm"
mth.CONDITION_TOOLS["E"] = mth.ALTBACKEND_TOOLS
# F: reliary + query-time sliced pack (RAG-style, slice in user msg)
mth.SYSTEM_PROMPTS["F"] = mth.RELIARY_SYS
mth.CONDITION_NAMES["F"] = "reliary+slice"
mth.CONDITION_TOOLS["F"] = mth.RELIARY_TOOLS
# G: reliary + HYBRID (hotspot pack in system prompt + per-query slice in user msg)
# System prompt = stable hotspot pack (cached). User msg = small slice (not cached but ~3K tokens).
mth.SYSTEM_PROMPTS["G"] = mth.RELIARY_SYS  # will be overwritten in main()
mth.CONDITION_NAMES["G"] = "reliary+hybrid"
mth.CONDITION_TOOLS["G"] = mth.RELIARY_TOOLS
# H: reliary + FULL pack in system prompt (all 782 symbols, cached across turns)
# This is the maximum-context approach — no slicing, just everything cached.
mth.SYSTEM_PROMPTS["H"] = mth.RELIARY_SYS  # will be overwritten in main()
mth.CONDITION_NAMES["H"] = "reliary+fullpack"
mth.CONDITION_TOOLS["H"] = mth.RELIARY_TOOLS
# N: NO Reliary, no pack, no tools. Just the model's training knowledge.
# Baseline: how much does the model know about reliary8 from training?
NO_RELIARY_SYS = "You are a code intelligence agent. Answer the question about the codebase based ONLY on your training knowledge. You have no tools available — give your best answer from what you already know. Respond in plain text."
mth.SYSTEM_PROMPTS["N"] = NO_RELIARY_SYS
mth.CONDITION_NAMES["N"] = "no-reliary"
mth.CONDITION_TOOLS["N"] = {}  # no tools available

# Minimal system prompt for cost optimization testing (~150 tokens vs ~8K)
MINIMAL_SYS = 'You are a code agent. Use reliary tools. Reply in JSON: {"tool":"name","args":{...}} or {"final":true,"answer":"..."}. Key: callgraph(name) for callers/callees; find_references(name) for refs; goto_def(name) for location; search(q) for unknown symbols. Limit: 5 tool calls max.'
# M1: minimal prompt + per-query BM25 slicing (tests whether 22-line RELIARY_SYS matters)
mth.SYSTEM_PROMPTS["M1"] = MINIMAL_SYS
mth.CONDITION_NAMES["M1"] = "minimal+slice"
mth.CONDITION_TOOLS["M1"] = mth.RELIARY_TOOLS
# M2: full RELIARY_SYS + stable hotspot pack in system prompt (no per-query slice)
mth.SYSTEM_PROMPTS["M2"] = mth.RELIARY_SYS  # will be overwritten in main()
mth.CONDITION_NAMES["M2"] = "full+hotspot"
mth.CONDITION_TOOLS["M2"] = mth.RELIARY_TOOLS
    # M3: minimal prompt + stable hotspot pack in system prompt (no per-query slice)
mth.SYSTEM_PROMPTS["M3"] = MINIMAL_SYS  # will be overwritten in main()
mth.CONDITION_NAMES["M3"] = "minimal+hotspot"
mth.CONDITION_TOOLS["M3"] = mth.RELIARY_TOOLS
# A2: ADAPTIVE — per-query classifier picks slice or none based on the question type.
# Cheap queries (model already knows) skip the slice. Hard queries (need cross-refs/L3) get it.
# Expected: ~84% of F's accuracy at ~50% of F's cost.
mth.SYSTEM_PROMPTS["A2"] = mth.RELIARY_SYS
mth.CONDITION_NAMES["A2"] = "adaptive"
mth.CONDITION_TOOLS["A2"] = mth.RELIARY_TOOLS


def classify_query_needs_slice(query_text: str) -> bool:
    """Return True if the query benefits from the sliced pack, False if model likely knows it.
    
    Based on N→F analysis:
    - N=3 queries: model knows from training, slice wastes tokens
    - N=0 F≥2 queries: slice is essential
    - bug_* queries: slice provides L3 surprise (N→F Δ = +1.8)
    - _crossref queries: slice provides caller lists (N→F Δ = +1.0)
    - _detail queries: slice provides specific values (N→F Δ = +1.4)
    - arch_* queries: model already knows (N=3 F=3, Δ=0) — skip
    - _discriminate queries: marginal gain (Δ=+0.2) — skip to save cost
    - _edge queries: marginal gain (Δ=+0.5) — skip
    - _what queries: moderate gain (Δ=+0.8) — skip
    """
    text = query_text.lower()
    # Always slice: bug detection and cross-references (biggest deltas)
    if "bug" in text or "issue" in text or "wrong" in text or "incorrect" in text or "missing" in text:
        return True
    if "call" in text or "caller" in text or "who uses" in text or "references" in text or "called by" in text:
        return True
    # Always slice: detail questions need specific values
    if "value" in text or "threshold" in text or "parameter" in text or "default" in text or "exactly" in text or "what number" in text:
        return True
    # Always slice: question mentions specific symbol names that might not be in training
    func_indicators = ["find_clusters", "skelhash", "skeleton_hash", "aggressive_skeleton", 
                       "maxwell", "should_drop", "detect_strategy", "callgraph", "is_definition_line"]
    if any(f in text for f in func_indicators):
        return True
    # Skip slice: architecture, discriminate, edge, what questions (model already knows or marginal gain)
    return False

# Global: full pack for condition F/G slicing (pre-built once)
FULL_PACK_FOR_SLICING = None

def run_session(cond, queries, model, seed, project, timeout_total=1800):
    """Run a single session with the given queries."""
    rng_idx = seed  # for any randomness in tasks
    sys_prompt = mth.SYSTEM_PROMPTS[cond]
    mth._sessions.clear()
    if cond in ("A", "D", "F", "G", "H", "M1", "M2", "M3", "A2"):
        mth._sessions["reliary"] = mth.MCPSession(mth.RELIARY_BIN, project, "reliary")
    if cond == "E":
        mth._sessions["altbackend"] = mth.MCPSession(mth.ALTBACKEND_BIN, project, "altbackend")
    messages = [{"role": "system", "content": sys_prompt}]
    
    # E2: Tool result cache — avoids repeating the same tool call across queries
    tool_cache = {}  # (tool_name, sorted_args_json) -> output string
    tool_cache_hits = 0
    
    # E3: Search interceptor — pre-check if the search term exists in the pack
    # Build a set of all symbol names from the full pack for fast lookup
    full_pack_symbol_names = set()
    if FULL_PACK_FOR_SLICING:
        for line in FULL_PACK_FOR_SLICING.split("\n"):
            if line.startswith("## "):
                name = line[3:].split("/")[0].strip()
                if name:
                    full_pack_symbol_names.add(name.lower())
    
    metrics = {
        "cond": cond, "cond_name": mth.CONDITION_NAMES.get(cond, cond),
        "model": model, "seed": seed, "queries": [],
        "total_wall_time": 0, "total_tool_calls": 0, "total_turns": 0,
        "total_tokens_in": 0, "total_tokens_out": 0,
        "total_weighted_cost": 0, "total_tool_bytes": 0,
        "total_dead_end_calls": 0, "total_score": 0,
        "total_cached_tokens": 0,
        "tool_cache_hits": 0,
    }
    t_start = time.time()
    for qi, query in enumerate(queries):
        if time.time() - t_start > timeout_total:
            break
        # FIX: Reset messages per query to avoid accumulating conversation history.
        # The original Python experiments were single-shot per query; the accumulated
        # messages inflated cost 8x (3K/query → 49K/query by query 63).
        messages = [{"role": "system", "content": sys_prompt}]
        # For conditions F and G: slice the full pack for this query and prepend
        if cond in ("F", "G", "M1") and FULL_PACK_FOR_SLICING:
            # Extract function names from the question text (handles abbreviations
            # like "findcl" -> "find_clusters" by parsing the question itself).
            func_names = _extract_func_names_from_question(query["question"])
            # Try the first function name found in the question
            query_text = func_names[0] if func_names else query["question"]
            sliced = slice_pack_for_query(FULL_PACK_FOR_SLICING, query_text, 10)
            if sliced:
                user_content = f"## Relevant codebase context (sliced for this query)\n\n{sliced}\n\n---\n\nQuestion: {query['question']}"
            else:
                user_content = query["question"]
        elif cond == "A2" and FULL_PACK_FOR_SLICING and classify_query_needs_slice(query["question"]):
            # Adaptive: only slice when the classifier says it's worth it
            func_names = _extract_func_names_from_question(query["question"])
            query_text = func_names[0] if func_names else query["question"]
            sliced = slice_pack_for_query(FULL_PACK_FOR_SLICING, query_text, 10)
            if sliced:
                user_content = f"## Relevant codebase context (sliced for this query)\n\n{sliced}\n\n---\n\nQuestion: {query['question']}"
            else:
                user_content = query["question"]
        else:
            user_content = query["question"]
        messages.append({"role": "user", "content": user_content})
        q_m = {"query_id": query["id"], "tool_calls": 0, "turns": 0,
               "tokens_in": 0, "tokens_out": 0, "weighted_cost": 0,
               "tool_bytes": 0, "dead_end_calls": 0, "score": 0, "answer": "",
               "tool_names": []}
        for turn in range(MAX_TURNS_PER_QUERY):
            if time.time() - t_start > timeout_total:
                q_m["answer"] = "(session timeout)"
                break
            if turn == MAX_TURNS_PER_QUERY - 1:
                messages.append({"role": "user",
                    "content": "Give your FINAL answer now. ONE LINE: {\"final\": true, \"answer\": \"...\"}"})
            resp = deepseek_chat(messages, model=model, max_tokens=1500,
                                 timeout=60, disable_thinking=True)
            if "error" in resp:
                q_m["answer"] = f"(error: {str(resp['error'])[:200]})"
                break
            msg = resp.get("choices", [{}])[0].get("message", {})
            content = msg.get("content", "") or msg.get("reasoning_content", "")
            usage = resp.get("usage", {})
            q_m["tokens_in"] += usage.get("prompt_tokens", 0)
            q_m["tokens_out"] += usage.get("completion_tokens", 0)
            cached = usage.get("prompt_cache_hit_tokens", 0) or usage.get("cached_tokens", 0)
            metrics["total_cached_tokens"] += cached
            q_m["turns"] = turn + 1
            action_type, action = mth.parse_llm_response(content)
            if action_type == "final":
                q_m["answer"] = action.get("answer", content[:2000])
                q_m["weighted_cost"] = q_m["tokens_in"] + 4 * q_m["tokens_out"]
                break
            elif action_type == "tool":
                tool_name = action.get("tool", action.get("name", ""))
                tool_args = action.get("args", action.get("arguments", action))
                if isinstance(tool_args, str):
                    try:
                        tool_args = json.loads(tool_args) if tool_args.strip().startswith("{") else {"query": tool_args}
                    except Exception:
                        tool_args = {"query": tool_args}
                
                # E2: Tool result cache — only for pack conditions (F, G, D)
                # and only cache successful results (not dead-ends)
                cache_key = (tool_name, json.dumps(tool_args, sort_keys=True))
                if cond in ("F", "G", "D", "M1", "M2", "M3", "A2") and cache_key in tool_cache:
                    output = tool_cache[cache_key]
                    tool_cache_hits += 1
                    q_m["tool_names"].append(f"{tool_name}(cached)")
                    q_m["tool_bytes"] += len(output.encode())
                # E3: Search interceptor — only for pack conditions (F, G, D)
                # and only if the symbol is genuinely not in the pack
                elif cond in ("F", "G", "D", "M1", "M2", "M3", "A2") and "search" in tool_name and full_pack_symbol_names:
                    search_term = (tool_args.get("query") or tool_args.get("q") or 
                                  tool_args.get("pattern") or tool_args.get("name") or "").strip()
                    if search_term:
                        sl = search_term.lower()
                        # Check if the search term or any part of it is in the pack
                        found_exact = sl in full_pack_symbol_names
                        found_partial = any(sl in name or name in sl for name in full_pack_symbol_names)
                        if not found_exact and not found_partial:
                            output = f"(no search results: symbol '{search_term}' not found in codebase index)"
                            tool_cache[cache_key] = output
                            q_m["tool_calls"] += 1
                            q_m["tool_names"].append(tool_name)
                            q_m["tool_bytes"] += len(output.encode())
                            # This is a CORRECT dead-end (symbol doesn't exist), don't count as bad
                            messages.append({"role": "assistant", "content": content})
                            messages.append({"role": "user", "content": f"Tool result:\n{output[:8000]}"})
                            continue
                    # Symbol might exist — make the real call
                    output, _ = mth.execute_tool(cond, tool_name, tool_args)
                    is_dead = any(output.strip().startswith(m) for m in ["(no ", "(no results)", "(no definition", "(no trace", "(no search", "(error", "(altbackend error", "(grep error", "(read error"])
                    if not is_dead:
                        tool_cache[cache_key] = output
                    q_m["tool_calls"] += 1
                    q_m["tool_names"].append(tool_name)
                    q_m["tool_bytes"] += len(output.encode())
                    if is_dead:
                        q_m["dead_end_calls"] += 1
                else:
                    output, _ = mth.execute_tool(cond, tool_name, tool_args)
                    # E2: Only cache NON-dead-end results (dead-ends are not useful to reuse)
                    is_dead = any(output.strip().startswith(m) for m in ["(no ", "(no results)", "(no definition", "(no trace", "(no search", "(error", "(altbackend error", "(grep error", "(read error"])
                    if not is_dead:
                        tool_cache[cache_key] = output
                    q_m["tool_calls"] += 1
                    q_m["tool_names"].append(tool_name)
                    q_m["tool_bytes"] += len(output.encode())
                    if is_dead:
                        q_m["dead_end_calls"] += 1
                messages.append({"role": "assistant", "content": content})
                messages.append({"role": "user", "content": f"Tool result:\n{output[:8000]}"})
            else:
                q_m["answer"] = content[:2000]
                q_m["weighted_cost"] = q_m["tokens_in"] + 4 * q_m["tokens_out"]
                break
        q_m["score"] = mth.score_answer(query, q_m["answer"])
        if q_m["answer"] and not q_m["answer"].startswith("("):
            messages.append({"role": "assistant", "content": q_m["answer"]})
        for k in ["tokens_in", "tokens_out", "tool_calls", "turns",
                  "weighted_cost", "tool_bytes", "dead_end_calls", "score"]:
            metrics[f"total_{k}"] += q_m[k]
        metrics["queries"].append(q_m)
    metrics["total_wall_time"] = time.time() - t_start
    metrics["tool_cache_hits"] = tool_cache_hits
    mth._close_sessions()
    return metrics

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--model", default="deepseek-v4-flash")
    p.add_argument("--seeds", nargs="+", type=int, default=[42])
    p.add_argument("--conditions", default="A,D")
    p.add_argument("--max-queries", type=int, default=10, help="cap probe count (for quick testing)")
    p.add_argument("--project", default="$HOME/src/reliary8", help="codebase root path")
    p.add_argument("--probes", default="results/reliary8_probes.json", help="probes JSON relative to bench/")
    p.add_argument("--out", default=None)
    args = p.parse_args()
    # Load pack for this project
    global PACK_PATH
    PACK_PATH = f"/tmp/{os.path.basename(args.project.rstrip('/'))}-pack.md"
    queries = load_queries(args.probes)[:args.max_queries]
    # Use --auto for condition D (gate + hotspot, no probe-knowledge)
    focused = build_auto_pack(args.project) if "D" in args.conditions.split(",") else None
    install_pack_as_system_prompt(focused)
    # Build full pack for conditions F, G, M1 (query-time slicing)
    global FULL_PACK_FOR_SLICING
    if "F" in args.conditions.split(",") or "G" in args.conditions.split(",") or "M1" in args.conditions.split(",") or "A2" in args.conditions.split(","):
        FULL_PACK_FOR_SLICING = build_full_pack(args.project)
    # Condition G: hybrid — stable hotspot pack in system prompt + per-query slice in user msg
    if "G" in args.conditions.split(","):
        hotspot_pack = build_auto_pack(args.project)  # stable, cached system prompt
        if hotspot_pack:
            mth.SYSTEM_PROMPTS["G"] = mth.RELIARY_SYS + f"\n\n## Codebase reference (stable hotspot pack)\n\n{hotspot_pack[:20000]}"
    # Condition H: FULL pack in system prompt (cached across turns)
    if "H" in args.conditions.split(",") and FULL_PACK_FOR_SLICING:
        mth.SYSTEM_PROMPTS["H"] = mth.RELIARY_SYS + f"\n\n## Complete codebase reference (full holographic pack)\n\n{FULL_PACK_FOR_SLICING[:80000]}"
    # Condition M2: full RELIARY_SYS + stable hotspot pack in system prompt (no per-query slice)
    if "M2" in args.conditions.split(","):
        hotspot_pack = build_auto_pack(args.project)
        if hotspot_pack:
            mth.SYSTEM_PROMPTS["M2"] = mth.RELIARY_SYS + f"\n\n## Codebase (hotspot)\n\n{hotspot_pack[:15000]}"
    # Condition M3: minimal prompt + stable hotspot pack in system prompt (no per-query slice)
    if "M3" in args.conditions.split(","):
        hotspot_pack = build_auto_pack(args.project)
        if hotspot_pack:
            mth.SYSTEM_PROMPTS["M3"] = MINIMAL_SYS + f"\n\n## Codebase (hotspot)\n\n{hotspot_pack[:15000]}"
    out_path = args.out or f"results/reliary8_session_{int(time.time())}.jsonl"
    all_runs = []
    for seed in args.seeds:
        for cond in args.conditions.split(","):
            print(f"\n=== seed={seed} cond={cond} ({mth.CONDITION_NAMES.get(cond,cond)}) ===", file=sys.stderr)
            try:
                r = run_session(cond, queries, args.model, seed, args.project)
                all_runs.append(r)
                # Per-tool breakdown
                from collections import Counter
                all_tool_names = []
                for q in r["queries"]:
                    all_tool_names.extend(q.get("tool_names", []))
                tool_counts = Counter(all_tool_names)
                tool_str = ", ".join(f"{n}={c}" for n, c in tool_counts.most_common())
                print(f"  score={r['total_score']}/{len(queries)*3} wc={r['total_weighted_cost']} cached={r['total_cached_tokens']} t={r['total_wall_time']:.1f}s")
                print(f"  tools: {tool_str}")
            except Exception as e:
                print(f"ERROR: {e}", file=sys.stderr)
                all_runs.append({"cond": cond, "seed": seed, "error": str(e)})
            mth._close_sessions()
    RESULTS_DIR = HERE / "results"
    with open(RESULTS_DIR / Path(out_path).name, "w") as f:
        for r in all_runs:
            f.write(json.dumps(r) + "\n")
    print(f"\nDone. Output: {RESULTS_DIR / Path(out_path).name}")

if __name__ == "__main__":
    main()
